### ISSUE TITLE
Views - Login - RATED 5

### ISSUE THREAD

**Issue by n810tran** [ultimated1228/ticketHandler#10]
- [x] The Login view will be displayed when the URL path is '/login'.
- [x] This view will be rendered with the login view, on the login layout, with the title of 'Log In' and no user type defined.
- [x] If the user is already logged in, they will be automatically redirected away from this view to the Dashboard page instead.
- [x] No Sequelize queries will need to run in order to render this view, however this view will be connected to the login.js script, which will post a request to authenticate using Sequelize to our server upon form submission.
- [x] No userType will be added to this particular view.

This view should receive the required values based on context, but also

1. title: STRING
2. layout: STRING

**Comment by ultimated1228** [comment]
created convention loggedIn and loggedOut to identify if the user is logged in or out.  This will need to remain consistent across the handlebar files, and logic built out accordingly.
