### ISSUE TITLE
Set up server file to use custom Helper methods - RATED 1

### ISSUE THREAD

**Issue by n810tran** [ultimated1228/ticketHandler#20]
## Helpers
These custom helpers are tools which `express-handlebars` will be able to apply to our template views.

- [ ] We will need to modify the `server.js` file to apply these helpers to our handlebars view engine.

**Comment by ultimated1228** [comment]
I believe this is the code that needs to go within the server file:
// Inform Express.js which template engine we're using
app.engine('handlebars', hbs.engine);
app.set('view engine', 'handlebars');
