### ISSUE TITLE
Models - Seeds - RATED 3

### ISSUE THREAD

**Issue by n810tran** [ultimated1228/ticketHandler#9]
## This App emulates an internal system:
All users of this application will be seeded directly by a DBA - we are emulating a business domain where the general population is not able to enroll with our application through signing up.

## To do:
- [x] Seed sample user data. Ensure that all hooks run upon creation.
- [x] (optional) Seed sample ticket data. Ensure all hooks run upon creation.
- [x] (optional, conditional on if ticket seeds exist) Seed sample log data.

**Comment by ultimated1228** [comment]
seed was created, pushing this back to a todo task just because I can't test the hooks at this point.
